version: '3'

services:
  db:
    container_name: challenge-db
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/database_data/
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge
    ports:
      - '5432:5432'
    volumes:
    - .:/var/lib/postgresql/data
